### PR TITLE
Pointing out that the nabo matrix must stay in scope.

### PR DESCRIPTION
**Pull request by tcies**
This cost me an entire day of looking for bugs. Grrr.

### CODE REVIEW

**Comment by HannesSommer** [comment]
Yes, this is a very problematic thing as it is typically not expected like it is!

Btw. this was also the core behind https://github.com/ethz-asl/libnabo/issues/34 as it can also store the reference to a temporary, which will silently happen if implicit type casting is necessary (not exact type match). I should have explained that back then... Sorry.

I think the best would be to take a pointer instead of a reference or even a shared pointer. At least temporaries are then prohibited. 
And I also believe it will make people more think about the expected live time of matrix, without looking into the documentation.

Talking about life time : I think the better term for the documentation would be that it needs to _stay alive_ or in memory at least as long as the nabo object.
Staying in scope is only the appropriate way to achieve that for local variables.

**Comment by tcies** [comment]
ok to test

**Comment by tcies** [comment]
stayinalive
Alive it is. Good to got then? Thanks for clarifying about #34!

**Comment by HannesSommer** [comment]
Yes, lgtm for the moment. For the future I added #39 .

**Comment by tcies** [comment]
:+1: :+1: :+1: thanks for caring!

**Comment by tcies** [comment]
Could you merge? I don't have the rights...

**Pull request merged**
