### PR TITLE
catkin not required for pure cmake packages

### PR DESCRIPTION
**Pull request by Timple**
This prevens rosdep resolving in ROS2

### CODE REVIEW

**Comment by pomerlef** [comment]
ok to test

**Comment by Timple** [comment]
If it speeds-up the review (or reduces risk), I can make the flag:

```xml
<run_depend condition="$ROS_VERSION == 1">catkin</run_depend>
```

**Comment by pomerlef** [comment]
yes, could you add that line (in libpointmatcher too). I'll try to process the PRs next week.

**Review by pomerlef — APPROVED** [review]

**Comment by patriksc** [comment]
Hi! The change in the `package.xml` from this merge is causing issues when building our library **COVINS**: https://github.com/VIS4ROB-lab/covins 

As soon as we call `catkin build <xzy>` (e.g. `catkin build eigen_catkin`), catkin throws 
`Error(s): The "run_depend" tag must not have the following attributes: condition`, caused by `libnabo/package.xml`. 

We found a workaround for now and removed the `libnabo` dependency, but maybe you want to consider whether this change is technically really necessary, since it seem like there might be some compatibility issues (we experienced this on 3 different machines with both Ubuntu 18 and Ubuntu 20).

**Comment by Timple** [comment]
Ow dear, that is a regression from my side. I forgot to add the new package format:

```xml
<package format="3">
```
Which supports the `condition` flag. PR incoming

**Comment by patriksc** [comment]
Indeed, would as well expect CI catches this... Anyway, no problem, thanks for the quick reply and for taking care of this.

**Pull request merged**
