### PR TITLE
Install any.hpp

### PR DESCRIPTION
**Pull request by HannesSommer**
This installs the new `any.hpp` into `include/nabo` (was missing before). One drawback is that the third-party tagging gets lost this way. Is that a problem?

### CODE REVIEW

**Comment by HannesSommer** [comment]
This is kind of urgent, because currently most dependers probably fail to build.

**Comment by stephanemagnenat** [comment]
> One drawback is that the third-party tagging gets lost this way.

Could we imagine to install in `nabo/third_party/`? For the sake of simplicity, we could match that locally and move `any.hpp` from `third_party/` to `nabo/third_party/`.

**Comment by HannesSommer** [comment]
Sure. I've just committed this "move". Looks cleaner to me :).

**Comment by HannesSommer** [comment]
I'm merging this to reduce the urgency (I'm pretty sure these changes only improve things). We can still patch later if it turns out not to be the final solution.

**Pull request merged**
